---
- name: Restart all hosts and ensure they're up
  hosts: all
  serial: 1
  become: true
  tasks:
    - block:
        - name: Restart host
          become: yes
          reboot:
            reboot_timeout: 300
            pre_reboot_delay: 0
            post_reboot_delay: 30
            test_command: uptime

      rescue:
        - name: Send Discord message
          uri:
            url: "{{ lookup ('env', 'DISCORD_REBOOT_FAILED_WEBHOOK') }}"
            method: POST
            headers:
              Content-Type: "application/json"
            body_format: json
            body: '{"content": "@everyone Reboot failed on {{ ansible_host | default(inventory_hostname) }}: {{ ansible_failed_result }}!"}'
          delegate_to: localhost
